openapi: 3.0.0
info:
  title: Books
  description: Books API
  version: 0.1.9
servers:
  - url: https://sql-render.onrender.com/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /books:
    get:
      tags:
        - Books
      responses:
        "200":
          description: get books data
    post:
      tags:
        - Books
      requestBody:
        description: create new book
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              properties:
                title:
                  type: string
                author:
                  type: string
      responses:
        '201':
          description: create new book successfully